### ISSUE TITLE
Might not be an official ROS package

### ISSUE THREAD

**Issue by jwhendy** [ros-melodic-arch/ros-melodic-viso2-ros#2]
This library also appears not to be tracked by ROS via the [distribution.yaml](https://github.com/ros/rosdistro/blob/master/melodic/distribution.yaml), at least for melodic. It is in [indigo's](https://github.com/ros/rosdistro/blob/master/indigo/distribution.yaml). It's also still [on the wiki](http://wiki.ros.org/viso2_ros). Reminds me of [the issue on fcl](https://github.com/ros-melodic-arch/ros-melodic-fcl/issues/1).

**Comment by acxz** [comment]
No other packages depend on it, so I believe it would be safe to just remove it from the AUR and the organization here.

It seems as tho it would also be safe to remove [ros-melodic-libviso2](https://aur.archlinux.org/packages/ros-melodic-libviso2/).

**Comment by jwhendy** [comment]
Re. this and the other package, what is the exact protocol? Like you just delete this entry from ros-melodic-arch and AUR so it no longer exists? Or do we just rename the AUR package to something like `libviso2` and then make it an orphan?

**Comment by acxz** [comment]
I would just delete the repo from ros-melodic-arch and the package in the AUR. No need to rename it if the pkgbuild will still be heavily based on the ros-melodic-arch stack. In any case, @bionade24 can offer more advice.

**Comment by bionade24** [comment]
If you want to extract it, then make it the clear way and rename it. For such cases, `replaces=`, `conflicts=` and `provides=` exist.

**Comment by acxz** [comment]
What exactly do we put in replaces conflicts and provides before we delete it? Or do we put this things in the other packages fields? I am a bit lost on how to archive this repository and delete it.

**Comment by bionade24** [comment]
You only have to do this in the new package. So that pacman knows if it installs the new package, it won't break any deps but conflict in the filesystem. Normally you don't want to allow to switch back easily with pacman's replace dialog, so letting the old `PKGBUILD` as it is will be totally fine. Yes, you could add `conflicts=()` to the old one too, but that would only be bloat and one unnecessary rebuild.

**Comment by acxz** [comment]
Do you mind taking care of this and archiving the repo, then? It would be nice to get rid of this issue.
